<?php 
$productCollection = $block->getProductCollection(); 
$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');

?> 

<!-- <html>
  <head>
    <link rel="stylesheet" href="owlcarousel/owl.carousel.min.css" />
    <link rel="stylesheet" href="owlcarousel/owl.theme.default.min.css" /> 
    <script src="jquery.min.js"></script>
<script src="owlcarousel/owl.carousel.min.js"></script>
  </head>
    <body> -->
        <div class="carousel-wrap"> 
          <div class="owl-carousel" id="owlslider">
          <?php foreach ($productCollection as $product) { 
            // echo "<pre>";print_r($product->getData());
                  $productImage = $imageBlock->getImage($product, 'category_page_grid'); 
          ?>
            <div class="item">
                <img src="<?php echo $product->getProductUrl(); ?>" /><?php echo $productImage->toHtml()?>
                <span><?php  echo $product->getName() . '<br />';?></span>
                <span><?php  echo $product->getPrice() . '<br />';?></span> 
             </div>
<?php } ?>            
          </div>
        </div>
<script type="text/javascript">
    /* require([
        'jquery',
        'owlcarousel'
        ], function ($) {
            'use strict';
                $(".owl-carousel").owlCarousel({
                autoPlay: 3000,
                margin:20,
                items : 20,
                itemsDesktop : [1199,20],
                itemsDesktopSmall : [979,20],
                itemsTablet : [768,20],
                navigation : true,
                pagination : false
          });
    });*/

   /* {
        "#owlslider": {
            "owlcarousel": {
                    "navigation" : true,
                    "center": true,
                    "margin":20,
                    "responsiveClass":true,
                    "responsive":{
                        "0":{
                            "items":1,
                            "nav":true
                        },
                        "600":{
                            "items":5,
                            "nav":true
                        },
                        "1000":{
                            "items":10,
                            "nav":true
                        }
                    }
                }
        }
    }*/

</script>
    <!-- </body>
</html> -->