
<div class="field address_attribute required">
    <label class="label" for="address_attribute">
      <span><?= $block->escapeHtml(__('Address Attribute')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="address_attribute" id="address_attribute" value="" title="<?= $block->escapeHtmlAttr(__('Address Attribute')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>
