<?php 
	// $block->getPrice();
	$_productCollection = $block->getProductCollection();
	$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');
	 $buttonTitle = __('Add to Cart');
	
	$loadedcollection = $imageBlock->getLoadedProductCollection();
	// $currentProduct = $block->getProduct();
// echo "<pre>";print_r(get_class_methods($currentProduct));

// $regularPrice = $currentProduct->getPriceInfo()->getPrice('regular_price');
	// $attributes = $_productCollection->getTypeInstance(true)->getConfigurableAttributes($product);
	// echo "<pre>";print_r(get_class_methods($attributes));
	// echo "----------------------------<pre>";print_r($_productCollection->getPriceInfo()->getPrice('regular_price'));die();
	/*echo "<pre>";print_r(get_class_methods($imageBlock));
	echo "<pre>";print_r(($imageBlock->getChildHtml()));*/
	// echo "<pre>";print_r(get_class_methods($loadedcollection));
?>
<div class="carousel-wrap">
    <div class="owl-carousel" id="owlslider">
        <?php foreach ($_productCollection as $product) { 
			$type_id = $product->getData('type_id');
		    	//$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
				//$products = $objectManager->create('Magento\Catalog\Model\Product')->load($product->getId());
        		//$block->getPrice($product->getId());
				//$price = $products->getPriceInfo()->getPrice('regular_price');//->getMinRegularAmount();//->getPrice('regular_price');//->getProduct();
// $productprices = $block->getPrice($product->getId()) ;
// echo $productprices->getMinRegularAmount();
		    //echo "<pre>";print_r(get_class_methods($price));
			//echo ($price);
				/*if($type_id == 'configurable' && $price){

				echo $price->getMinRegularAmount().'-'.$price->getMaxRegularAmount();	
				}*/
		    $productImage = $imageBlock->getImage($product, 'category_page_grid');

		    // echo "<pre>";print_r($product->getData('custom_product_type'));
		    $data = explode(',',$product->getData('custom_product_type'));
		     


		?>
        <div class="item">
        	<a href="<?=$product->getProductUrl()?>">
            	<img src="<?=$product->getProductUrl()?>" /><?php echo $productImage->toHtml()?>
        	</a>
            <span><?=$product->getName()?></span>
            <span>
                <?php 
				$i=0;
				foreach($data as $value):
					if($i < 2 ){
						$attr = $product->getResource()->getAttribute('custom_product_type');
				        if ($attr->usesSource()): ?>
                <?php $option_value = $attr->getSource()->getOptionText($value);?>
                <p><?php echo $option_value; ?></p>

                <?php 
				    	endif;
			    	$i++;
			    }
				endforeach;
			    ?>
            </span>
            <?php 
			foreach($loadedcollection as $listProduct){
				if($listProduct->getEntityId() == $product->getEntityId()){
					if($type_id == 'configurable'){ ?>
                    <div class='price-box'>
		                <span class="price">
		                    <?php
		                    /*if($listProduct->getData('min_price') !== $listProduct->getData('max_price')) {
								echo $listProduct->getData('min_price').'-'.$listProduct->getData('max_price');
							}else{
								echo $listProduct->getData('minimal_price');
							}*/
							if($type_id == 'configurable'){
								$price = $block->getPrice($product->getId());
							echo $price->getMinRegularAmount().'-'.$price->getMaxRegularAmount();	
							}else{
								echo $listProduct->getData('minimal_price');
							}
							?>
		                </span>
		    
		            </div>
            <?php } 
			    	else {  ?>
			    		<span><?=round($listProduct->getPrice())?></span>
			
            <?php } 
				}
			}?>
			<div class="actions">
	           <button type="submit"
	                   title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
	                   class="action primary tocartnewcolor"
	                   id="product-addtocart-button">
	               <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
	           </button>
	           <?= $block->getChildHtml('', true) ?>
	       </div>
        </div>
        
        <?php 	} 
		?>
    </div>
</div>
<!-- <a href="<?php  //echo $product->getProductUrl();?>"> -->
<!-- </a> -->