<?php 

$productCollection = $block->getProductCollection(); 
$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');
const PARAM_NAME_BASE64_URL = 'r64';
const PARAM_NAME_URL_ENCODED = 'uenc';
use Magento\Framework\App\Action\Action; 
use Magento\Rss\Block\Catalog\AbstractCatalog;
$_productCollection = $block->getProductCollection();

?> 
<div class="carousel-wrap mycustom"> 
    <div class="owl-carousel" id="owlslider">
        <?php foreach ($productCollection as $product) { 
            $productImage = $imageBlock->getImage($product, 'category_page_grid'); 
            $postParams = $block->getAddToCartPostParams($product); ?>
    
        <div class="item">
            <img src="<?php echo $product->getProductUrl(); ?>" /><?php echo $productImage->toHtml()?>
            <div class="product details product-item-details">
                <strong class="product name product-item-name">
                    <a class="product-item-link"
                       href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                        <?=/* @noEscape */ $product->getData('name')?>
                    </a>
                </strong>
                <span><?= round($product->getFinalPrice()) ?></span> 
                <span><?php 
                    if($product->getData('special_price')!== null){?>
                        <span><?php echo "Special Price : ".round($product->getData('special_price'));?></span>
                    <?php } ?>
                </span>
                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                    <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                    <?php echo $block->getBlockHtml('formkey')?>
                    <?php $storeManager = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Store\Model\StoreManagerInterface'); ?>
                        <button type="submit"
                                title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                class="action tocart primary">
                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                        </button>
                </form> 
                <a href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($product) ?>' class="action towishlist" data-action="add-to-wishlist"><span>'. ('Add to Wish List') . '</span>
                </a>
                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                <a href="#"
                   class="action tocompare"
                   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($product); ?>'
                   role="button">
                    <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                </a>
                <!-- <div class="actions-secondary" data-role="add-to-links">
                    <div class="action towishlist">
                        <a <?= /* @noEscape */ $block->getLinkAttributes() ?> class="wishlist-custom">
                            <span class="text"><?= $block->escapeHtml($product->getLabel()) ?></span>
                            <span data-bind="text: wishlist().counter" class="counter qty"></span>
                        </a>
                    </div>
                </div> -->
            </div>
        </div>
        <?php }?>
    </div>
</div>
<script type="text/x-magento-init">
{
"*": {
        "Magento_Ui/js/core/app": {
        "components": {
        "wishlist": {
        "component": "Magento_Wishlist/js/view/wishlist"
                }
            }
        }
    }
}

</script>