<?php 

 // echo $this->getData('content');
//  echo "here containt show|||||||||||";
//  // echo $this->getChildHtml('logo2');
//  // echo $this->getBlockHtml('logo2');
//  echo "----------------------------------";
//  // echo $this->getChildChildHtml('test.topmenu','test.block2');
// // echo '<pre>';
// //  print_r(get_class_methods($this));
// //  print_r(get_class($block));
// //  print_r(get_class_methods($block));
//  // echo $block->getLayout()->getBlock('test.block1')->toHtml();
//  echo "----------------------------------";
//  // echo $block->helper;
//  echo "----------------------------------";
//  echo $block->getLayout()->getBlock('test.block2')->toHtml();
//  echo "-------------------------++++++++++++Template++++++++++---------";
//  echo $block->getTemplate(); echo "<br>"."*******************************************************";
// //echo $block->getLayout(); 
// echo "<br>***********//////////////-----------";
//  echo $block->getBaseUrl();
//  print_r($block->getCacheKeyInfo());
//  echo $block->getChildData('test.topmenu');
//  echo $block->hasData();//1
//  echo "<br>!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!<br>";
//  echo $block->serialize();//content="test value" type="Magento\Framework\View\Element\Template" module_name=""
//  echo "-----------------------========area===========================---------<br>";
//  echo $block->getRequest()."////////////";
//  echo $block->getNameInLayout();
//  echo $block->getUiId();//data-ui-id="test-topmenu"
//  // echo $block->getBlockId();
//  // echo $block->getArea();//frontend

//  echo "<br>----------------------------------";
//  echo $block->getLayout()
//             ->createBlock(\Magento\Framework\View\Element\Template::class)
//             ->setTemplate('Magento_Cms::html/testing.phtml')
//             ->toHtml();//cms block
//  echo "----------------------------------";
//  echo $block->getLayout()
//             ->createBlock(\Magento\Cms\Block\Block::class)
//             ->setBlockId('block3')
//             ->toHtml();//static block
//  echo "----------------EXECUTE------------------";
// // echo $block->getLayout();
//  echo $block->getCodeByFrontName()."<br>";
//  echo $block->getDefaultRouter();
// echo $block->getLayout()
//             ->createBlock(\Magento\Framework\View\Element\Template::class)
//             ->setTemplate('Magento_Cms::html/container.phtml')
//             ->toHtml();
//             echo "<br>::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::";
// echo $block->getLayout()
//             ->createBlock(\Magento\Framework\View\Element\Template::class)
//             ->setTemplate('Magento_Cms::html/container.phtml')
//             ->toHtml();
// echo "----------------------------------";

// echo $block->getLayout()
//             ->createBlock(\Magento\Cms\Block\Block::class)
//             ->setBlockId('block4')
//             ->toHtml();
// echo "----------------------------------";
 // echo $this->getChildChildHtml('test.topmenu');
 /*$block = $this->frameworkViewLayout
    ->createBlock(
        "Magento\Module\Block\Hello",
        "block_name",
        [
            'data' => [
                'my_arg' => 'testvalue'
            ]
        ]  
    )
    ->setData('area', 'frontend')
    ->setTemplate($template)
    ->toHtml();*/

?>

<?xml version="1.0"?>
<!--
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd" layout="2columns-left">
    <body>
        <referenceContainer name="header-wrapper">
<!--             <referenceBlock name="ui-menu ui-widget ui-widget-content ui-corner-all" remove="true">
            </referenceBlock>
 -->        </referenceContainer>

        <referenceContainer name="header-panel">
            <container name="left-section">
                <container name="logo1" htmlClass="logo" htmlTag="div">
                    <block class="Magento\Framework\View\Element\Template" name="top.logo1" template="Magento_Search::form.mini.phtml">
                        <arguments>
                            <argument name="configProvider" xsi:type="object">Magento\Search\ViewModel\ConfigProvider</argument>
                        </arguments>
                    </block>
                </container>
            </container>
            <container name="middle-section">
                <container name="Searchbar1" htmlClass="block-search" htmlTag="div">
                    <block class="Magento\Framework\View\Element\Template" name="top.search1"  after="logo" before="minicart" template="Magento_Search::form.mini.phtml">
                        <arguments>
                            <argument name="configProvider" xsi:type="object">Magento\Search\ViewModel\ConfigProvider</argument>
                        </arguments>
                    </block>
                </container>
            </container>
             <container name="right-section" htmlTag="div" htmlClass="right">
                    <block class="Magento\Checkout\Block\Cart\Sidebar" name="minicart1" as="minicart" after="logo" template="Magento_Checkout::cart/minicart.phtml">
                <arguments>
                    <argument name="jsLayout" xsi:type="array">
                        <item name="types" xsi:type="array"/>
                        <item name="components" xsi:type="array">
                            <item name="minicart_content" xsi:type="array">
                                <item name="component" xsi:type="string">Magento_Checkout/js/view/minicart</item>
                                <item name="config" xsi:type="array">
                                    <item name="template" xsi:type="string">Magento_Checkout/minicart/content</item>
                                </item>
                                <item name="children" xsi:type="array">
                                    <item name="subtotal.container" xsi:type="array">
                                        <item name="component" xsi:type="string">uiComponent</item>
                                        <item name="config" xsi:type="array">
                                            <item name="displayArea" xsi:type="string">subtotalContainer</item>
                                        </item>
                                        <item name="children" xsi:type="array">
                                            <item name="subtotal" xsi:type="array">
                                                <item name="component" xsi:type="string">uiComponent</item>
                                                <item name="config" xsi:type="array">
                                                    <item name="template" xsi:type="string">Magento_Checkout/minicart/subtotal</item>
                                                </item>
                                            </item>
                                        </item>
                                    </item>
                                    <item name="extra_info" xsi:type="array">
                                        <item name="component" xsi:type="string">uiComponent</item>
                                        <item name="config" xsi:type="array">
                                            <item name="displayArea" xsi:type="string">extraInfo</item>
                                        </item>
                                    </item>
                                    <item name="promotion" xsi:type="array">
                                        <item name="component" xsi:type="string">uiComponent</item>
                                        <item name="config" xsi:type="array">
                                            <item name="displayArea" xsi:type="string">promotion</item>
                                        </item>
                                    </item>
                                </item>
                            </item>
                        </item>
                    </argument>
                </arguments>
            </block>
            </container>
        </referenceContainer>
        <referenceContainer name="content">
            <referenceContainer name="main-left">
                <container name="main-left-up-section">
                    <block class="Magento\Cms\Block\Block" name="left-section-up-main-page">
                        <arguments>
                          <argument name="block_id" xsi:type="string">categoryleftup</argument>
                        </arguments>
                    </block>
                </container>
                <container name="main-left-down-section">
                    <block class="Magento\Cms\Block\Block" name="left-section-down-main-page">
                        <arguments>
                          <argument name="block_id" xsi:type="string">categoryleftdown</argument>
                        </arguments>
                    </block>
                </container>
            </referenceContainer>
            <referenceContainer name="main-right-up">
                <container name="main-right-middle-section">
                    <block class="Magento\Cms\Block\Block" name="right-section-main-page">
                        <arguments>
                          <argument name="block_id" xsi:type="string">categoryrightmiddle</argument>
                        </arguments>
                    </block>
                </container>
                <container name="main-right-right-up-section">
                    <block class="Magento\Cms\Block\Block" name="right-section-up-main-page">
                        <arguments>
                          <argument name="block_id" xsi:type="string">categoryrightrightup</argument>
                        </arguments>
                    </block>
                </container>
                <container name="main-right-right-down-section">
                    <block class="Magento\Cms\Block\Block" name="right-section-down-main-page">
                        <arguments>
                          <argument name="block_id" xsi:type="string">categoryrightrightdown</argument>
                        </arguments>
                    </block>
                </container>
            </referenceContainer> 
            <referenceContainer name="main-right-down">
                <container name="main-right-up-newarrival-product">
                    <block class="Magento\Cms\Block\Block" name="right-section-down-main-page-newarrival">
                        <arguments>
                          <argument name="block_id" xsi:type="string">newproduct</argument>
                        </arguments>
                    </block>
                </container>
                <container name="main-right-down-bestseller-product">
                    <block class="Magento\Cms\Block\Block" name="right-section-down-main-page-bestseller">
                        <arguments>
                          <argument name="block_id" xsi:type="string">bestseller</argument>
                        </arguments>
                    </block>
                </container>
            </referenceContainer>       
        </referenceContainer>
        <!-- <referenceContainer name="main"> -->
            <!-- <container name="block2" htmlClass="wrap-midd" htmlTag="div">
            <container name="block1" htmlClass="wrap-test" htmlTag="div">
             -->    <!-- <block class="Magento\Cms\Block\Block" name="test.block1">
                    <arguments>
                      <argument name="block_id" xsi:type="string">block1</argument>
                    </arguments>
                </block> -->

                <!-- <referenceContainer name="content">
                    <block class="Magento\Framework\View\Element\Template" name="test.topmenu" as="topmenucustom" template="Magento_Cms::html/topmenu.phtml">
                        <arguments>
                            <argument name="content" xsi:type="string">test value</argument>
                        </arguments>
                        <block class="Magento\Cms\Block\Block" name="test.block2" before="-">
                            <arguments>
                              <argument name="block_id" xsi:type="string">block2</argument>
                            </arguments>
                        </block>
                    </block>
                </referenceContainer> -->

                <!-- <block class="Magento\Framework\View\Element\Text" name="middle.text" after="test.block2">
                    <arguments>
                      <argument translate="true" name="text" xsi:type="string">This is middle text</argument>
                    </arguments>
                </block> -->
            
            <!-- <container name="left-section" htmlClass="left" htmlTag="div">
                
                <block class="Magento\Theme\Block\Html\Header\Logo" name="logo2">
                    <arguments>
                        <argument name="logoPathResolver" xsi:type="object">Magento\Theme\ViewModel\Block\Html\Header\LogoPathResolver</argument>
                        <argument name="logo_size_resolver" xsi:type="object">Magento\Theme\ViewModel\Block\Html\Header\LogoSizeResolver</argument>
                    </arguments>
                </block>
            </container> -->

           <!--  <container name="middle-section" htmlClass="middle" htmlTag="div">
                <block class="Magento\Framework\View\Element\Template" name="top.search1"  after="logo2" template="Magento_Search::form.mini.phtml">
                    <arguments>
                        <argument name="configProvider" xsi:type="object">Magento\Search\ViewModel\ConfigProvider</argument>
                    </arguments>
                    
                </block>
            </container> -->

            <!-- <container name="right-section" htmlTag="div" htmlClass="right">
                    <block class="Magento\Checkout\Block\Cart\Sidebar" name="minicart1" as="minicart" after="logo" template="Magento_Checkout::cart/minicart.phtml">
                <arguments>
                    <argument name="jsLayout" xsi:type="array">
                        <item name="types" xsi:type="array"/>
                        <item name="components" xsi:type="array">
                            <item name="minicart_content" xsi:type="array">
                                <item name="component" xsi:type="string">Magento_Checkout/js/view/minicart</item>
                                <item name="config" xsi:type="array">
                                    <item name="template" xsi:type="string">Magento_Checkout/minicart/content</item>
                                </item>
                                <item name="children" xsi:type="array">
                                    <item name="subtotal.container" xsi:type="array">
                                        <item name="component" xsi:type="string">uiComponent</item>
                                        <item name="config" xsi:type="array">
                                            <item name="displayArea" xsi:type="string">subtotalContainer</item>
                                        </item>
                                        <item name="children" xsi:type="array">
                                            <item name="subtotal" xsi:type="array">
                                                <item name="component" xsi:type="string">uiComponent</item>
                                                <item name="config" xsi:type="array">
                                                    <item name="template" xsi:type="string">Magento_Checkout/minicart/subtotal</item>
                                                </item>
                                            </item>
                                        </item>
                                    </item>
                                    <item name="extra_info" xsi:type="array">
                                        <item name="component" xsi:type="string">uiComponent</item>
                                        <item name="config" xsi:type="array">
                                            <item name="displayArea" xsi:type="string">extraInfo</item>
                                        </item>
                                    </item>
                                    <item name="promotion" xsi:type="array">
                                        <item name="component" xsi:type="string">uiComponent</item>
                                        <item name="config" xsi:type="array">
                                            <item name="displayArea" xsi:type="string">promotion</item>
                                        </item>
                                    </item>
                                </item>
                            </item>
                        </item>
                    </argument>
                </arguments>
            </block>
            </container>
            </container> 
        </container>
        </referenceContainer> -->
         
    </body>
</page>
<!-- <move element="name.of.an.element" destination="name.of.destination.element" as="new_alias" after="name.of.element.after" before="name.of.element.before"/> -->