<?php
   $_helper = $this->helper(Category\Attribute\Helper\Data::class);
   $_product = $block->getProduct();

   $viewModel = $block->getData('viewModel');

   echo "before <pre>";
   // print_r($viewModel->getCurrentCategoryDetails());
   $alldata = $viewModel->getCurrentCategoryDetails();
   // print_r($alldata);exit;
   $subtitle = $alldata['subtitle']; 
   $isvisible = $alldata['is_visible_subtitle'];
   $material = $alldata['category_material'];
   $color = $alldata['category_color'];
   $image = $alldata['category_image'];
   $top = $alldata['category_top'];
   if ($isvisible !== 0){
      echo $subtitle."<br>";
   }
   $topdata = $viewModel->addWidget($alldata['category_top']);
   echo $topdata;
   $materialArray = ($material) ? explode(',', $material) : [];

   $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
   $eavConfig = $objectManager->get('\Magento\Eav\Model\Config');
   $attribute = $eavConfig->getAttribute('catalog_product','material1');//->setStoreId(0);
   $options = $attribute->getSource()->getAllOptions();
   foreach ($options as $_option) {
      if(in_array($_option['value'],$materialArray)){
          echo $_option['label'] . ",";
      }
   }
   echo "<br>".$color .  "<br>" ;
   // $content = $alldata['category_top']->getContent(); 
   // echo $alldata->filterOutputHtml($content);
   
   // $this->_filterProvider->getPageFilter()->filter($top);
   ?>
<img src="<?php echo $image; ?>"  width="400" height="400"/>
