<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js">
        </script>
        <script>
        require([ 'jquery'], function($){
            $(function () {
                $('#discount').on('change', function() {
                    var discountvalue = $( "#discount" ).find( "option:selected" ).val(); 
                    $('#custom_price_cal').val(discountvalue);
                });
            });
        });
        </script> 
    </head>
    <body>
        <form>
 <!-- <input type="hidden" name="custom_price" value="" id="custom_price_cal"> -->

        <div>
        	<span>Discount</span>
        	<select name="discount" id="discount">
                <option value="low">Low 10% OFF</option>
        	  	<option value="medium">Medium</option>	
        	  	<option value="high">High</option>
        	</select>
        </div>
        </form>
    </body>
</html>
    <?php 
       /* $data = explode(',',$product->getData('discount'));

        foreach($data as $value):            
    ?>
        <?php 
        $attr = $product->getResource()->getAttribute('discount');
        if ($attr->usesSource()): ?>
            <?php 
                $option_value = $attr->getSource()->getOptionText($value);
            ?>
            <p><?php echo $option_value; ?></p>

        <?php endif;?>
    <?php endforeach;*/?>