<?php 

$product = $block->getProduct();
$subtitle = $product->getData('subtitle');
$viewModel = $block->getData('viewModel');
$blockTitle = $this->getData('title');
$product_custom_name = $product->getData('product_custom_name');
$is_visible_subtitle = $product->getData('is_visible_subtitle');
$product_color = $product->getData('product_color');
$product_material = $product->getData('product_material');

	if($is_visible_subtitle !== 0)
	{	
    echo "------------------------------------";
		echo "<br>".$subtitle;
	}
	echo "<br>".$blockTitle;
    echo "rrrrrrrrrrrrrrrrrrrrrrr";
	echo "<br>".$product_color; 
	echo "<br>".$product_custom_name;   
	$topdata = $product->getData('product_top');
   echo "<br>".$topdata."<br>";

   $materialArray = ($product_material	) ? explode(',', $product_material) : [];
   $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
   $eavConfig = $objectManager->get('\Magento\Eav\Model\Config');
   $attribute = $eavConfig->getAttribute('catalog_product','material');//->setStoreId(0);
   $options = $attribute->getSource()->getAllOptions();
   // echo "<pre>";
   // print_r($options);

   foreach ($options as $_option) {
      if(in_array($_option['value'],$materialArray)){
          echo $_option['label'] . "  ";
      }
   }
// echo $product_material;
?>
<div class="stock actual-qty"> <span class="value" > </span> </div> 